_extends: rx-nostr:.github/release-drafter/base.yml

header: https://www.npmjs.com/package/@rx-nostr/crypto/v/$RESOLVED_VERSION

name-template: crypto_$RESOLVED_VERSION
tag-template: crypto_$RESOLVED_VERSION
tag-prefix: crypto_
include-paths:
  - packages/crypto
