# document: https://github.com/release-drafter/release-drafter

template: $CHANGES
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
change-title-escapes: \<*_& # You can add # and @ to disable mentions, and add ` to disable code blocks.

categories:
  - title: ðŸš¨ BREAKING CHANGES
    labels:
      - breaking change
  - title: ðŸš€ New Features
    labels:
      - feature
  - title: ðŸ› Bug Fixes
    labels:
      - bugfix
  - title: ðŸ“– Docs
    labels:
      - documentation
  - title: ðŸ§° Maintenance
    labels:
      - chore

version-resolver:
  major:
    labels:
      - breaking change
  minor:
    labels:
      - feature
  patch:
    labels:
      - bugfix
      - chore
  default: patch

autolabeler:
  - label: feature
    branch:
      - /^feat\//
      - /^feature\//
    title:
      - /^feat.*:/
  - label: bugfix
    branch:
      - /^fix\//
    title:
      - /^fix.*:/
  - label: documentation
    files:
      - "*.md"
    branch:
      - /^docs{0,1}\//
    title:
      - /^docs.*:/
  - label: chore
    branch:
      - /chore\//
    title:
      - /^chore.*:/
