_extends: rx-nostr:.github/release-drafter/base.yml

header: https://www.npmjs.com/package/rx-nostr/v/$RESOLVED_VERSION

name-template: core@$RESOLVED_VERSION
tag-template: core@$RESOLVED_VERSION
tag-prefix: core@
include-paths:
  - packages/core
  - packages/docs
