<template><div><h1 id="operator" tabindex="-1"><a class="header-anchor" href="#operator" aria-hidden="true">#</a> Operator</h1>
<h2 id="function" tabindex="-1"><a class="header-anchor" href="#function" aria-hidden="true">#</a> function</h2>
<h3 id="uniq" tabindex="-1"><a class="header-anchor" href="#uniq" aria-hidden="true">#</a> uniq()</h3>
<div class="language-typescript" data-ext="ts"><pre v-pre class="language-typescript"><code><span class="token keyword">function</span> <span class="token function">uniq</span><span class="token punctuation">(</span>
  flushes<span class="token operator">?</span><span class="token operator">:</span> ObservableInput<span class="token operator">&lt;</span><span class="token builtin">unknown</span><span class="token operator">></span>
<span class="token punctuation">)</span><span class="token operator">:</span> MonoTypeOperatorFunction<span class="token operator">&lt;</span>EventPacket<span class="token operator">></span><span class="token punctuation">;</span>
</code></pre></div><h3 id="latest" tabindex="-1"><a class="header-anchor" href="#latest" aria-hidden="true">#</a> latest()</h3>
<div class="language-typescript" data-ext="ts"><pre v-pre class="language-typescript"><code><span class="token keyword">function</span> <span class="token function">latest</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token operator">:</span> MonoTypeOperatorFunction<span class="token operator">&lt;</span>EventPacket<span class="token operator">></span><span class="token punctuation">;</span>
</code></pre></div><h3 id="latest-each" tabindex="-1"><a class="header-anchor" href="#latest-each" aria-hidden="true">#</a> latestEach()</h3>
<div class="language-typescript" data-ext="ts"><pre v-pre class="language-typescript"><code><span class="token keyword">function</span> <span class="token generic-function"><span class="token function">latestEach</span><span class="token generic class-name"><span class="token operator">&lt;</span><span class="token constant">K</span><span class="token operator">></span></span></span><span class="token punctuation">(</span>
  <span class="token function-variable function">key</span><span class="token operator">:</span> <span class="token punctuation">(</span>packet<span class="token operator">:</span> EventPacket<span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token constant">K</span>
<span class="token punctuation">)</span><span class="token operator">:</span> MonoTypeOperatorFunction<span class="token operator">&lt;</span>EventPacket<span class="token operator">></span><span class="token punctuation">;</span>
</code></pre></div><h3 id="verify" tabindex="-1"><a class="header-anchor" href="#verify" aria-hidden="true">#</a> verify()</h3>
<div class="language-typescript" data-ext="ts"><pre v-pre class="language-typescript"><code><span class="token keyword">function</span> <span class="token function">verify</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token operator">:</span> MonoTypeOperatorFunction<span class="token operator">&lt;</span>EventPacket<span class="token operator">></span><span class="token punctuation">;</span>
</code></pre></div><h3 id="filter-kind" tabindex="-1"><a class="header-anchor" href="#filter-kind" aria-hidden="true">#</a> filterKind()</h3>
<div class="language-typescript" data-ext="ts"><pre v-pre class="language-typescript"><code><span class="token keyword">function</span> <span class="token generic-function"><span class="token function">filterKind</span><span class="token generic class-name"><span class="token operator">&lt;</span><span class="token constant">K</span> <span class="token keyword">extends</span> Nostr<span class="token punctuation">.</span>Kind<span class="token operator">></span></span></span><span class="token punctuation">(</span>
  kind<span class="token operator">:</span> <span class="token constant">K</span>
<span class="token punctuation">)</span><span class="token operator">:</span> MonoTypeOperatorFunction<span class="token operator">&lt;</span>EventPacket<span class="token operator">></span><span class="token punctuation">;</span>
</code></pre></div><h3 id="batch" tabindex="-1"><a class="header-anchor" href="#batch" aria-hidden="true">#</a> batch()</h3>
<div class="language-typescript" data-ext="ts"><pre v-pre class="language-typescript"><code><span class="token keyword">function</span> <span class="token function">batch</span><span class="token punctuation">(</span>
  mergeFilter<span class="token operator">:</span> MergeFilter
<span class="token punctuation">)</span><span class="token operator">:</span> OperatorFunction<span class="token operator">&lt;</span>ReqPacket<span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token punctuation">,</span> ReqPacket<span class="token operator">></span><span class="token punctuation">;</span>

<span class="token keyword">type</span> <span class="token class-name">MergeFilter</span> <span class="token operator">=</span> <span class="token punctuation">(</span>a<span class="token operator">:</span> Nostr<span class="token punctuation">.</span>Filter<span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token punctuation">,</span> b<span class="token operator">:</span> Nostr<span class="token punctuation">.</span>Filter<span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token punctuation">)</span> <span class="token operator">=></span> Nostr<span class="token punctuation">.</span>Filter<span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token punctuation">;</span>
</code></pre></div><h3 id="chunk" tabindex="-1"><a class="header-anchor" href="#chunk" aria-hidden="true">#</a> chunk()</h3>
<div class="language-typescript" data-ext="ts"><pre v-pre class="language-typescript"><code><span class="token keyword">function</span> <span class="token function">chunk</span><span class="token punctuation">(</span>
  <span class="token function-variable function">predicate</span><span class="token operator">:</span> <span class="token punctuation">(</span>f<span class="token operator">:</span> Nostr<span class="token punctuation">.</span>Filter<span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token builtin">boolean</span><span class="token punctuation">,</span>
  <span class="token function-variable function">toChunk</span><span class="token operator">:</span> <span class="token punctuation">(</span>f<span class="token operator">:</span> Nostr<span class="token punctuation">.</span>Filter<span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token punctuation">)</span> <span class="token operator">=></span> Nostr<span class="token punctuation">.</span>Filter<span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token punctuation">[</span><span class="token punctuation">]</span>
<span class="token punctuation">)</span><span class="token operator">:</span> MonoTypeOperatorFunction<span class="token operator">&lt;</span>ReqPacket<span class="token operator">></span><span class="token punctuation">;</span>
</code></pre></div><h3 id="complete-on-timeout" tabindex="-1"><a class="header-anchor" href="#complete-on-timeout" aria-hidden="true">#</a> completeOnTimeout()</h3>
<div class="language-typescript" data-ext="ts"><pre v-pre class="language-typescript"><code><span class="token keyword">function</span> <span class="token generic-function"><span class="token function">completeOnTimeout</span><span class="token generic class-name"><span class="token operator">&lt;</span><span class="token constant">T</span><span class="token operator">></span></span></span><span class="token punctuation">(</span>time<span class="token operator">:</span> <span class="token builtin">number</span><span class="token punctuation">)</span><span class="token operator">:</span> MonoTypeOperatorFunction<span class="token operator">&lt;</span><span class="token constant">T</span><span class="token operator">></span><span class="token punctuation">;</span>
</code></pre></div></div></template>


