<template><div><h1 id="rxreq" tabindex="-1"><a class="header-anchor" href="#rxreq" aria-hidden="true">#</a> RxReq</h1>
<h2 id="function" tabindex="-1"><a class="header-anchor" href="#function" aria-hidden="true">#</a> function</h2>
<h3 id="create-rx-forward-req" tabindex="-1"><a class="header-anchor" href="#create-rx-forward-req" aria-hidden="true">#</a> createRxForwardReq()</h3>
<div class="language-typescript" data-ext="ts"><pre v-pre class="language-typescript"><code><span class="token keyword">function</span> <span class="token function">createRxForwardReq</span><span class="token punctuation">(</span>subId<span class="token operator">?</span><span class="token operator">:</span> <span class="token builtin">string</span><span class="token punctuation">)</span><span class="token operator">:</span> RxReq<span class="token operator">&lt;</span><span class="token string">"forward"</span><span class="token operator">></span> <span class="token operator">&amp;</span> RxReqController<span class="token punctuation">;</span>
</code></pre></div><h3 id="create-rx-backward-req" tabindex="-1"><a class="header-anchor" href="#create-rx-backward-req" aria-hidden="true">#</a> createRxBackwardReq()</h3>
<div class="language-typescript" data-ext="ts"><pre v-pre class="language-typescript"><code><span class="token keyword">function</span> <span class="token function">createRxBackwardReq</span><span class="token punctuation">(</span>
  subIdBase<span class="token operator">?</span><span class="token operator">:</span> <span class="token builtin">string</span>
<span class="token punctuation">)</span><span class="token operator">:</span> RxReq<span class="token operator">&lt;</span><span class="token string">"backward"</span><span class="token operator">></span> <span class="token operator">&amp;</span> RxReqController<span class="token punctuation">;</span>
</code></pre></div><h3 id="create-rx-oneshot-req" tabindex="-1"><a class="header-anchor" href="#create-rx-oneshot-req" aria-hidden="true">#</a> createRxOneshotReq()</h3>
<div class="language-typescript" data-ext="ts"><pre v-pre class="language-typescript"><code><span class="token keyword">function</span> <span class="token function">createRxOneshotReq</span><span class="token punctuation">(</span>req<span class="token operator">:</span> <span class="token punctuation">{</span>
  filters<span class="token operator">:</span> Nostr<span class="token punctuation">.</span>Filter<span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token punctuation">;</span>
  subId<span class="token operator">?</span><span class="token operator">:</span> <span class="token builtin">string</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token operator">:</span> RxReq<span class="token operator">&lt;</span><span class="token string">"oneshot"</span><span class="token operator">></span><span class="token punctuation">;</span>
</code></pre></div><h2 id="interface" tabindex="-1"><a class="header-anchor" href="#interface" aria-hidden="true">#</a> interface</h2>
<h3 id="rx-req" tabindex="-1"><a class="header-anchor" href="#rx-req" aria-hidden="true">#</a> RxReq&lt;S&gt;</h3>
<div class="language-typescript" data-ext="ts"><pre v-pre class="language-typescript"><code><span class="token keyword">interface</span> <span class="token class-name">RxReq<span class="token operator">&lt;</span><span class="token constant">S</span> <span class="token keyword">extends</span> RxReqStrategy <span class="token operator">=</span> RxReqStrategy<span class="token operator">></span></span> <span class="token punctuation">{</span>
  <span class="token keyword">get</span> <span class="token function">strategy</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token operator">:</span> <span class="token constant">S</span><span class="token punctuation">;</span>
  <span class="token keyword">get</span> <span class="token function">rxReqId</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token operator">:</span> <span class="token builtin">string</span><span class="token punctuation">;</span>
  <span class="token function">getReqObservable</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token operator">:</span> Observable<span class="token operator">&lt;</span>ReqPacket<span class="token operator">></span><span class="token punctuation">;</span>
  <span class="token function">pipe</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token operator">:</span> RxReq<span class="token punctuation">;</span>
  <span class="token function">pipe</span><span class="token punctuation">(</span>op1<span class="token operator">:</span> OperatorFunction<span class="token operator">&lt;</span>ReqPacket<span class="token punctuation">,</span> ReqPacket<span class="token operator">></span><span class="token punctuation">)</span><span class="token operator">:</span> RxReq<span class="token punctuation">;</span>
  <span class="token generic-function"><span class="token function">pipe</span><span class="token generic class-name"><span class="token operator">&lt;</span><span class="token constant">A</span><span class="token operator">></span></span></span><span class="token punctuation">(</span>
    op1<span class="token operator">:</span> OperatorFunction<span class="token operator">&lt;</span>ReqPacket<span class="token punctuation">,</span> <span class="token constant">A</span><span class="token operator">></span><span class="token punctuation">,</span>
    op2<span class="token operator">:</span> OperatorFunction<span class="token operator">&lt;</span><span class="token constant">A</span><span class="token punctuation">,</span> ReqPacket<span class="token operator">></span>
  <span class="token punctuation">)</span><span class="token operator">:</span> RxReq<span class="token punctuation">;</span>
  <span class="token generic-function"><span class="token function">pipe</span><span class="token generic class-name"><span class="token operator">&lt;</span><span class="token constant">A</span><span class="token punctuation">,</span> <span class="token constant">B</span><span class="token operator">></span></span></span><span class="token punctuation">(</span>
    op1<span class="token operator">:</span> OperatorFunction<span class="token operator">&lt;</span>ReqPacket<span class="token punctuation">,</span> <span class="token constant">A</span><span class="token operator">></span><span class="token punctuation">,</span>
    op2<span class="token operator">:</span> OperatorFunction<span class="token operator">&lt;</span><span class="token constant">A</span><span class="token punctuation">,</span> <span class="token constant">B</span><span class="token operator">></span><span class="token punctuation">,</span>
    op3<span class="token operator">:</span> OperatorFunction<span class="token operator">&lt;</span><span class="token constant">B</span><span class="token punctuation">,</span> ReqPacket<span class="token operator">></span>
  <span class="token punctuation">)</span><span class="token operator">:</span> RxReq<span class="token punctuation">;</span>
  <span class="token generic-function"><span class="token function">pipe</span><span class="token generic class-name"><span class="token operator">&lt;</span><span class="token constant">A</span><span class="token punctuation">,</span> <span class="token constant">B</span><span class="token punctuation">,</span> <span class="token constant">C</span><span class="token operator">></span></span></span><span class="token punctuation">(</span>
    op1<span class="token operator">:</span> OperatorFunction<span class="token operator">&lt;</span>ReqPacket<span class="token punctuation">,</span> <span class="token constant">A</span><span class="token operator">></span><span class="token punctuation">,</span>
    op2<span class="token operator">:</span> OperatorFunction<span class="token operator">&lt;</span><span class="token constant">A</span><span class="token punctuation">,</span> <span class="token constant">B</span><span class="token operator">></span><span class="token punctuation">,</span>
    op3<span class="token operator">:</span> OperatorFunction<span class="token operator">&lt;</span><span class="token constant">B</span><span class="token punctuation">,</span> <span class="token constant">C</span><span class="token operator">></span><span class="token punctuation">,</span>
    op4<span class="token operator">:</span> OperatorFunction<span class="token operator">&lt;</span><span class="token constant">C</span><span class="token punctuation">,</span> ReqPacket<span class="token operator">></span>
  <span class="token punctuation">)</span><span class="token operator">:</span> RxReq<span class="token punctuation">;</span>
  <span class="token generic-function"><span class="token function">pipe</span><span class="token generic class-name"><span class="token operator">&lt;</span><span class="token constant">A</span><span class="token punctuation">,</span> <span class="token constant">B</span><span class="token punctuation">,</span> <span class="token constant">C</span><span class="token punctuation">,</span> <span class="token constant">D</span><span class="token operator">></span></span></span><span class="token punctuation">(</span>
    op1<span class="token operator">:</span> OperatorFunction<span class="token operator">&lt;</span>ReqPacket<span class="token punctuation">,</span> <span class="token constant">A</span><span class="token operator">></span><span class="token punctuation">,</span>
    op2<span class="token operator">:</span> OperatorFunction<span class="token operator">&lt;</span><span class="token constant">A</span><span class="token punctuation">,</span> <span class="token constant">B</span><span class="token operator">></span><span class="token punctuation">,</span>
    op3<span class="token operator">:</span> OperatorFunction<span class="token operator">&lt;</span><span class="token constant">B</span><span class="token punctuation">,</span> <span class="token constant">C</span><span class="token operator">></span><span class="token punctuation">,</span>
    op4<span class="token operator">:</span> OperatorFunction<span class="token operator">&lt;</span><span class="token constant">C</span><span class="token punctuation">,</span> <span class="token constant">D</span><span class="token operator">></span><span class="token punctuation">,</span>
    op5<span class="token operator">:</span> OperatorFunction<span class="token operator">&lt;</span><span class="token constant">D</span><span class="token punctuation">,</span> ReqPacket<span class="token operator">></span>
  <span class="token punctuation">)</span><span class="token operator">:</span> RxReq<span class="token punctuation">;</span>
<span class="token punctuation">}</span>

<span class="token keyword">type</span> <span class="token class-name">RxReqStrategy</span> <span class="token operator">=</span> <span class="token string">"forward"</span> <span class="token operator">|</span> <span class="token string">"backward"</span> <span class="token operator">|</span> <span class="token string">"oneshot"</span><span class="token punctuation">;</span>
</code></pre></div><h4 id="strategy" tabindex="-1"><a class="header-anchor" href="#strategy" aria-hidden="true">#</a> strategy</h4>
<h4 id="rx-req-id" tabindex="-1"><a class="header-anchor" href="#rx-req-id" aria-hidden="true">#</a> rxReqId</h4>
<h4 id="get-req-observable" tabindex="-1"><a class="header-anchor" href="#get-req-observable" aria-hidden="true">#</a> getReqObservable()</h4>
<h4 id="pipe" tabindex="-1"><a class="header-anchor" href="#pipe" aria-hidden="true">#</a> pipe()</h4>
<h3 id="rx-req-controller" tabindex="-1"><a class="header-anchor" href="#rx-req-controller" aria-hidden="true">#</a> RxReqController</h3>
<div class="language-typescript" data-ext="ts"><pre v-pre class="language-typescript"><code><span class="token keyword">interface</span> <span class="token class-name">RxReqController</span> <span class="token punctuation">{</span>
  <span class="token function">emit</span><span class="token punctuation">(</span>filters<span class="token operator">:</span> Nostr<span class="token punctuation">.</span>Filter<span class="token punctuation">[</span><span class="token punctuation">]</span> <span class="token operator">|</span> <span class="token keyword">null</span><span class="token punctuation">)</span><span class="token operator">:</span> <span class="token keyword">void</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span>
</code></pre></div></div></template>


