name: publish package

description: Publish the target package

# Requirement:
#   - uses: actions/setup-node
#   - permissions:
#       actions: write
#       checks: write
#       contents: write
#   - env:
#       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#       NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}

inputs:
  version:
    description: Version string.
    required: true
  package:
    description: Package name.
    required: true

runs:
  using: composite
  steps:
    - name: push new commit that updating package's version.
      uses: ./.github/actions/update-package-version
      with:
        version: ${{ inputs.version }}
        package: packages/${{ inputs.package }}
        commit_message_template: "version(${{ inputs.package }}): $VERSION"
        tag_template: ${{ inputs.package }}_$VERSION
        tag_force: true
    - name: npm publish
      shell: bash
      run: npx -y can-npm-publish packages/${{ inputs.package }} && npm publish -w packages/${{ inputs.package }}
