<template><div><h1 id="lazy-since-until-v1-2-0" tabindex="-1"><a class="header-anchor" href="#lazy-since-until-v1-2-0"><span>Lazy since/until (v1.2.0+)</span></a></h1>
<p><RouteLink to="/docs/first-step.html">First Step</RouteLink> でも説明したように、<code v-pre>RxReq</code> から <code v-pre>RxNostr</code> に向かって <code v-pre>ReqPacket</code> を送出するためには原則として <code v-pre>rxReq.emit()</code> を使います (Oneshot Strategy においては代わりに <code v-pre>createOneshotRxReq()</code> の引数を使います)。この引数は Nostr 標準の Filter オブジェクトとほぼ同一の型を持ちますが、<code v-pre>since</code> または <code v-pre>until</code> に数値の代わりに <code v-pre>() =&gt; number</code> 型の関数を渡すこともできます。</p>
<p><code v-pre>since</code>/<code v-pre>until</code> に関数を渡した場合、リレーに実際に送信される <code v-pre>since</code>/<code v-pre>until</code> の値は送信の直前に評価されます。このような <code v-pre>since</code>/<code v-pre>until</code> の遅延評価は特に WebSocket の再接続を考慮したときに便利です。例えば、現在よりも「未来」の投稿を購読するために <code v-pre>{ since: datetime }</code> フィルターを送信したとします。この購読が有効なうちに WebSocket の再接続が発生するとリレーには再度まったく同じ REQ が送信されますが、これはつまり再接続時点から見て「過去」のイベントをリレーに要求することを意味します。この振る舞いは時として望ましくありません。</p>
<p><code v-pre>{ since: datetime }</code> の代わりに <code v-pre>{ since: () =&gt; datetime }</code> フィルターを使用すると、再接続時点であらためて <code v-pre>since</code> が評価されます。rx-nostr はこのユースケースのために便利な <code v-pre>now()</code> 関数を公開しています。</p>
<div class="language-javascript" data-ext="js" data-title="js"><pre v-pre class="language-javascript"><code><span class="token keyword">import</span> <span class="token punctuation">{</span> createRxNostr<span class="token punctuation">,</span> createRxForwardReq<span class="token punctuation">,</span> now <span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">"rx-nostr"</span><span class="token punctuation">;</span>

<span class="token keyword">const</span> rxNostr <span class="token operator">=</span> <span class="token function">createRxNostr</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token keyword">await</span> rxNostr<span class="token punctuation">.</span><span class="token function">switchRelays</span><span class="token punctuation">(</span><span class="token punctuation">[</span><span class="token string">"wss://nostr.example.com"</span><span class="token punctuation">]</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

<span class="token keyword">const</span> rxReq <span class="token operator">=</span> <span class="token function">createRxForwardReq</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

<span class="token keyword">const</span> observable <span class="token operator">=</span> rxNostr<span class="token punctuation">.</span><span class="token function">use</span><span class="token punctuation">(</span>rxReq<span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">subscribe</span><span class="token punctuation">(</span>console<span class="token punctuation">.</span>log<span class="token punctuation">)</span><span class="token punctuation">;</span>

rxReq<span class="token punctuation">.</span><span class="token function">emit</span><span class="token punctuation">(</span><span class="token punctuation">{</span> <span class="token literal-property property">kinds</span><span class="token operator">:</span> <span class="token punctuation">[</span><span class="token number">1</span><span class="token punctuation">]</span><span class="token punctuation">,</span> <span class="token literal-property property">since</span><span class="token operator">:</span> now <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre></div></div></template>


