<template><div><h1 id="sending-event" tabindex="-1"><a class="header-anchor" href="#sending-event"><span>Sending EVENT</span></a></h1>
<p><code v-pre>RxNostr</code> の <code v-pre>send()</code> メソッドを通じて、書き込みが許可されているすべてのリレーに対して EVENT メッセージを送信することができます。</p>
<p><code v-pre>send()</code> の第一引数は <code v-pre>kind</code> と <code v-pre>content</code> のみが必須で残りが省略可能な event オブジェクトで、第二引数は省略可能のオプションで、特に <code v-pre>seckey</code> オプションに <code v-pre>nsec</code> 形式または HEX 形式の秘密鍵を指定可能です。省略されたパラメータは NIP-07 インターフェースを用いて自動的に計算されます。逆に、指定されたパラメータは指定された値が (たとえ不正な値だったとしても) 尊重されます。</p>
<div class="language-javascript line-numbers-mode" data-ext="js" data-title="js"><pre v-pre class="language-javascript"><code><span class="token keyword">import</span> <span class="token punctuation">{</span> createRxNostr <span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">"rx-nostr"</span><span class="token punctuation">;</span>

<span class="token keyword">const</span> rxNostr <span class="token operator">=</span> <span class="token function">createRxNostr</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token keyword">await</span> rxNostr<span class="token punctuation">.</span><span class="token function">switchRelays</span><span class="token punctuation">(</span><span class="token punctuation">[</span><span class="token string">"wss://nostr.example.com"</span><span class="token punctuation">]</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

<span class="token comment">// NIP-07 is required because the 2nd positional argument is omitted.</span>
rxNostr<span class="token punctuation">.</span><span class="token function">send</span><span class="token punctuation">(</span><span class="token punctuation">{</span>
  <span class="token literal-property property">kind</span><span class="token operator">:</span> <span class="token number">1</span><span class="token punctuation">,</span>
  <span class="token literal-property property">content</span><span class="token operator">:</span> <span class="token string">"Hello, Nostr!"</span><span class="token punctuation">,</span>
<span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="highlight-lines"><br><br><br><br><br><div class="highlight-line">&nbsp;</div><div class="highlight-line">&nbsp;</div><div class="highlight-line">&nbsp;</div><div class="highlight-line">&nbsp;</div><div class="highlight-line">&nbsp;</div></div><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>実際に送信される event オブジェクトの内容に興味がある場合もあるかもしれません。そのときは <code v-pre>send()</code> が内部的に使用している <code v-pre>getSignedEvent()</code> を直接使用することができます。</p>
<div class="language-javascript line-numbers-mode" data-ext="js" data-title="js"><pre v-pre class="language-javascript"><code><span class="token keyword">import</span> <span class="token punctuation">{</span> createRxNostr<span class="token punctuation">,</span> getSignedEvent <span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">"rx-nostr"</span><span class="token punctuation">;</span>

<span class="token keyword">const</span> rxNostr <span class="token operator">=</span> <span class="token function">createRxNostr</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token keyword">await</span> rxNostr<span class="token punctuation">.</span><span class="token function">switchRelays</span><span class="token punctuation">(</span><span class="token punctuation">[</span><span class="token string">"wss://nostr.example.com"</span><span class="token punctuation">]</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

<span class="token keyword">const</span> event <span class="token operator">=</span> <span class="token keyword">await</span> <span class="token function">getSignedEvent</span><span class="token punctuation">(</span><span class="token punctuation">{</span>
  <span class="token literal-property property">kind</span><span class="token operator">:</span> <span class="token number">1</span><span class="token punctuation">,</span>
  <span class="token literal-property property">content</span><span class="token operator">:</span> <span class="token string">"Hello, Nostr!"</span><span class="token punctuation">,</span>
<span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>event<span class="token punctuation">.</span>id<span class="token interpolation-punctuation punctuation">}</span></span><span class="token string"> will be sent.</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span><span class="token punctuation">;</span>

rxNostr<span class="token punctuation">.</span><span class="token function">send</span><span class="token punctuation">(</span>event<span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="highlight-lines"><br><br><br><br><br><div class="highlight-line">&nbsp;</div><div class="highlight-line">&nbsp;</div><div class="highlight-line">&nbsp;</div><div class="highlight-line">&nbsp;</div><br><br><br><div class="highlight-line">&nbsp;</div></div><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="handling-ok-messages" tabindex="-1"><a class="header-anchor" href="#handling-ok-messages"><span>Handling OK Messages</span></a></h2>
<p><code v-pre>use()</code> は送信した EVENT に対する OK Message を購読する Observable を返します。Observable は送信先のリレーの数と同じ数の OK Message を受け取ったときに complete、または何もメッセージを受信しないまま 30 秒経過したときに error で終了します。</p>
<div class="language-javascript" data-ext="js" data-title="js"><pre v-pre class="language-javascript"><code>rxNostr<span class="token punctuation">.</span><span class="token function">send</span><span class="token punctuation">(</span>event<span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">subscribe</span><span class="token punctuation">(</span><span class="token punctuation">(</span><span class="token parameter">packet</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span>
  console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">relay: </span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>packet<span class="token punctuation">.</span>from<span class="token interpolation-punctuation punctuation">}</span></span><span class="token string"> -> </span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>packet<span class="token punctuation">.</span>ok <span class="token operator">?</span> <span class="token string">"succeeded"</span> <span class="token operator">:</span> <span class="token string">"failed"</span><span class="token interpolation-punctuation punctuation">}</span></span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre></div><h2 id="write-on-a-subset-of-relays-v1-1-0" tabindex="-1"><a class="header-anchor" href="#write-on-a-subset-of-relays-v1-1-0"><span>Write on a subset of relays (v1.1.0+)</span></a></h2>
<p>構成された書き込み可能リレーのうちの一部だけにイベントを送信したい場合、 <code v-pre>scope</code> オプションにリレーの URL のリストを指定できます。
<code v-pre>scope</code> オプションに URL を指定しても、指定された URL が構成されていない場合には書き込みは発生しないことに注意してください。</p>
</div></template>


